---
# handlers file for zookeeper
# Only restart the zookeeper service when the service_control fact is True
- name: restart zookeeper
  service: name=zookeeper state=restarted
  when: service_control == True
  ignore_errors: yes
