---

- name: Create Temporary Storage Folder
  file:
    path: "{{ java_tmp_storage }}"
    state: directory

- name: Download Oracle Java RPM
  get_url:
    url: "{{ __java_oracle_download }}"
    headers: 'Cookie:oraclelicense=accept-secure-backup-cookie'
    dest: "{{ java_tmp_storage }}/{{ __java_oracle_rpm }}.rpm"
#    checksum: "{{ __java_oracle_download_checksum }}"

- name: Install Oracle Java
  package:
    name: "{{ java_tmp_storage }}/{{ __java_oracle_rpm }}.rpm"
    state: installed
    validate_certs: False
