---
# Setup Java on System

- name: Install add-apt-repostory
  become: yes
  apt: name=software-properties-common state=latest

# Adding Open Java repository
- name: Add Open Java8 Repository
  become: yes
  apt_repository: repo='ppa:openjdk-r/ppa'

# Updating cache
- name: Update apt cache if repository just added.
  apt: update_cache=yes

# Installing Java8
- name: Install Oracle Java 8
  become: yes
  apt: name={{item}} state=installed
  with_items:
    - openjdk-8-jdk
    - openjdk-8-jre

# Environment setup.
#- name: Set JAVA_HOME if configured.
#  template:
#    src: java_home.sh.j2
#    dest: /etc/profile.d/java_home.sh
 #   mode: 0644
